server:
 port: 7000
spring:
 application:
  name: provider-service

#eureka:
 #client:
  #registerWithEureka: true
  #fetchRegistry: true
  #serviceUrl:
   #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 #instance:
  #preferIpAddress: true
