zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
  
#   patient-info-service:
#      path: /patient-info-service/**
#      service-id: patient-info-service
#      
#   notification-service:
#      path: /notification-service/**
#      service-id: notification-service 
    
   provider-service:
      path: /provider-service/**
      service-id: provider-service
   patient-service:
      path: /patient-service/**
      service-id: patient-service
      
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000  
      
